### ISSUE TITLE
Add buildmimic code for MIMIC-IV-Note

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/mimic-code#1511]
### Discussed in https://github.com/MIT-LCP/mimic-code/discussions/1490

<div type='discussions-op-text'>

<sup>Originally posted by **fantamanatee** February 19, 2023</sup>
In the [Load MIMIC-IV into a PostgreSQL database tutorial](https://github.com/MIT-LCP/mimic-code/tree/main/mimic-iv/buildmimic/postgres#load-mimic-iv-into-a-postgresql-database), I noticed note events are not included. Since MIMIC IV note was published on Jan 6, is it possible to include MIMIC IV note data in a local postgresql database (while also following the postgresqk tutorial)?</div>

### TODO:

- [ ] Add schema for `discharge`, `discharge_detail`, `radiology`, `radiology_detail` tables
- [ ] Add load scripts
- [ ] Consider database systems other than psql
